<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.2</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <Authors>Hani Al Ziya</Authors>
    <Product>MouseGile</Product>
    <Description>Lightweight automatic mouse jiggler and productivity utility</Description>
    <ApplicationIcon>mousegile.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="mousegile.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.161" />
  </ItemGroup>

</Project>